[package]
name = "luminous"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
image = "0.24.7"
log = "0.4.20"
minifb = "0.25.0"
ocl = "0.19.4"
